OyunDukkani/Models/ErrorViewModel.cs
namespace OyunDukkani.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OyunDukkani/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OyunDukkani.Data;
using OyunDukkani.Models;
using System.Diagnostics;

namespace OyunDukkani.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly OyunlarContext db;
        public HomeController(ILogger<HomeController> logger, OyunlarContext _db)
        {
            _logger = logger;
            db = _db;
        }

        public IActionResult Index()
        {
            return View(db.oyunlar.ToList());
        }

        public IActionResult Privacy()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OyunDukkani/Controllers/OyunlarController.cs
using Microsoft.AspNetCore.Mvc;
using OyunDukkani.Data;
using System.Text;

namespace OyunDukkani.Controllers
{
    public class OyunlarController : Controller
    {
        private readonly OyunlarContext db;

        public OyunlarController(OyunlarContext _db)
        {
            db = _db;
        }
        public IActionResult Index()
        {
            return View(db.oyunlar.ToList());
        }

        public IActionResult Yeni()
        {
            string yeniBarkod;
            bool varMi;

            // Yeni bir barkod oluşturana kadar döngüde kalın
            do
            {
                yeniBarkod = BarkodUret(); // Rastgele 13 haneli sayı oluştur

                // Veritabanında aynı barkod numarası var mı diye kontrol edin
                varMi = db.oyunlar.Any(o => o.BarkodNumarasi == yeniBarkod);
            } while (varMi);

            // Yeni oyun modeli oluşturun ve barkod numarasını atayın
            var yeniOyun = new Oyunlar
            {
                BarkodNumarasi = yeniBarkod
            };
            return View(yeniOyun);
        }

        

        [HttpPost]
        public IActionResult Yeni(Oyunlar oyun)
        {
            if (ModelState.IsValid)
            {

                db.oyunlar.Add(oyun);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public string BarkodUret()
        {
            Random random = new Random();
            StringBuilder sb = new StringBuilder();

            for (int i = 0; i < 13; i++)
            {
                int digit = random.Next(10); 
                sb.Append(digit); 
            }

            string randomNumber = sb.ToString();
            return randomNumber;
        }
    }
}

OyunDukkani/Views/Home/Index.cshtml
@model List<OyunDukkani.Data.Oyunlar>
@{
    ViewBag.Title = "Data";
}


<h1>Oyunlarımız</h1>
<a asp-controller="Oyunlar" asp-action="Yeni">Yeni Girdi</a>

<table class="table">
    <thead>
        <tr>
            <th>Oyun Adı</th>
            <th>Fiyatı</th>
            <th>Platformu</th>
            <th>Barkod Numarası</th>
            <th>Tek Platform</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var oyun in Model)
        {
            <tr>
                <td>@(oyun.OyunAdi ?? "Bilgi Yok")</td>
                <td>@oyun.Fiyati</td>
                <td>@(oyun.Platformu ?? "Bilgi Yok")</td>
                <td>@(oyun.BarkodNumarasi ?? "Bilgi Yok")</td>
                <td>@(oyun.TekPlatform ? "Evet" : "Hayır")</td>
            </tr>
        }
    </tbody>
</table>

OyunDukkani/Views/Oyunlar/Index.cshtml
@model List<OyunDukkani.Data.Oyunlar>
@{
    ViewBag.Title = "Data";
}


<h1>Oyunlarımız</h1>
<a asp-action="Yeni">Yeni Girdi</a>

<table class="table">
    <thead>
        <tr>
            <th>Oyun Adı</th>
            <th>Fiyatı</th>
            <th>Platformu</th>
            <th>Barkod Numarası</th>
            <th>Tek Platform</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var oyun in Model)
        {
            <tr>
                <td>@(oyun.OyunAdi ?? "Bilgi Yok")</td>
                <td>@oyun.Fiyati</td>
                <td>@(oyun.Platformu ?? "Bilgi Yok")</td>
                <td>@(oyun.BarkodNumarasi ?? "Bilgi Yok")</td>
                <td>@(oyun.TekPlatform ? "Evet" : "Hayır")</td>
            </tr>
        }
    </tbody>
</table>

OyunDukkani/Views/Oyunlar/Yeni.cshtml
@model OyunDukkani.Data.Oyunlar
@{
    ViewData["Title"] = "Yeni Girdi";
}
<h1>Yeni Girdi</h1>


<form method="post">
    <div class="mb-3">
        <label asp-for="OyunAdi" class="form-label">Oyun Adı</label>
        <input asp-for="OyunAdi" type="text" class="form-control" />
        <span asp-validation-for="OyunAdi" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Fiyati" class="form-label">Fiyatı</label>
        <input asp-for="Fiyati" type="number" class="form-control" />
        <span asp-validation-for="Fiyati" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Platformu" class="form-label">Platformu</label>
        <input asp-for="Platformu" type="text" class="form-control" />
        <span asp-validation-for="Platformu" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="BarkodNumarasi" class="form-label">Barkod Numarası</label>
        @Model.BarkodNumarasi
        <input asp-for="BarkodNumarasi" class="form-control" readonly value="@Model.BarkodNumarasi" />
        <span asp-validation-for="BarkodNumarasi" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="TekPlatform" class="form-label">Tek Platform</label>
        <input asp-for="TekPlatform" type="checkbox" class="form-check-input" />
        <span asp-validation-for="TekPlatform" class="text-danger"></span>
    </div>
    <button class="btn btn-primary">Ekle</button>
    <a asp-action="Index" class="btn btn-secondary">İptal</a>
</form>

OyunDukkani/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OyunDukkani</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OyunDukkani.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OyunDukkani</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Oyunlar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OyunDukkani - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>